version: "3"

services:
    # image project
    app:
        build:
            context: .
            dockerfile: Dockerfile
        restart: unless-stopped
        working_dir: /var/www/
        volumes:
            - ./:/var/www
        depends_on:
            - redis
        networks:
            - laravel

    # nginx
    nginx:
        image: nginx:alpine
        restart: unless-stopped
        ports:
            - "8000:80"
        volumes:
            - ./:/var/www
            - ./docker/nginx/:/etc/nginx/conf.d/
        networks:
            - laravel

    # db postgresql
    db:
        image: postgres:13
        platform: linux/x86_64
        restart: unless-stopped
        environment:
            POSTGRES_DB: ${DB_DATABASE:-laravel}
            POSTGRES_USER: ${DB_USERNAME:-contato@phpfullstack.com.br}
            POSTGRES_PASSWORD: ${DB_PASSWORD:-admin}
        volumes:
            - ./.docker/postgres/dbdata:/var/lib/postgresql/data
        ports:
            - "5432:5432"
        networks:
            - laravel

    # pgAdmin
    pgadmin:
        image: dpage/pgadmin4
        platform: linux/x86_64
        restart: unless-stopped
        environment:
            PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL:-antonio@phpfullstack.com.br}
            PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD:-admin}
        ports:
            - "8080:80"
        networks:
            - laravel

    # redis
    redis:
        image: redis:latest
        networks:
            - laravel

networks:
    laravel:
        driver: bridge
